### ISSUE TITLE
360videosmetadata.py

### ISSUE THREAD

**Issue by AsrielLewis** [google/spatial-media#48] opened 2015-12-01 00:34 UTC
I was directed here by this page: https://support.google.com/youtube/answer/6178631?hl=en
and told to download the zip and run the 360videosmetadata.py script, but it is no longer included in the zip and I can't figure out how to make the current script(s) work.  I am new to python, and trying to inject 360 metadata into a equirectangular 360 video for youtube.  Any help appreciated.

**Comment by jprouty** [comment] 2015-12-01 05:22
That is indeed confusing! Sorry for the hassle. You can run the script as
per the instructions on this page
<https://github.com/google/spatial-media/tree/master/spatialmedia>. We'll
be sure to update the help article you linked. Thanks for bringing it to
our attention.

**Comment by JoshuaKolden** [comment] 2015-12-03 19:24
Those instructions also do not seem to work.

**Comment by suderman-google** [comment] 2015-12-03 20:14
If you are not in the current folder as the "spatialmedia" folder you will need to provide the entire path.

e.g. python ~/Desktop/spatial-media/spatialmedia -i ...

Alternatively we have an easier to use standalone application.
https://github.com/google/spatial-media/releases/tag/v2.0

**Comment by arpu** [comment] 2015-12-09 06:10
hello

how can i inject mkv web videos (vp9) ?

i use old 360videosmetadata.py i can set metadata , but youtube does not show the 360 degree player :(

**Comment by suderman-google** [comment] 2015-12-09 18:16
Support for webm was removed for our current tooling due to some platform issues. We plan to reintroduce support however for now you will need to use an mp4 file.

**Comment by AsrielLewis** [comment] 2015-12-10 21:48
When I download the standalone application to Downloads folder on MacBookPro/OS10.11.1 and open the injector tool, all the boxes are disabled, and when I highlight the equirectangular mp4 file on my desktop and select open, the app displays "No metadata found."

What am I doing wrong?

**Comment by suderman-google** [comment] 2015-12-10 21:58
No metadata found is fine as the file likely does not contain any spherical metadata. Once loaded you will be able to select checkboxes and save the file with new metadata. So no worries, everything is working fine :+1:

**Comment by AsrielLewis** [comment] 2015-12-10 22:05
Ok - that worked.  How do I preview the injected clip?  Thanks

**Comment by suderman-google** [comment] 2015-12-10 22:23
There are a few options:

1 - You can use the metadata tool to verify the correct data is injected. If you open the save file it will state metadata is present and update checkboxes to match the contained metadata.

2 - Use [KolorEyes](https://play.google.com/store/apps/details?id=fi.finwe.koloreyesandroid&hl=en) to inspect the content. It does not parse metadata at this point but it does provide playback for the video and you can toggle mono/stereo.

3 - If you want to test the full set (metadata and playback) the best method at this point is to uploaded to YouTube as an unlisted video and playback the video. Note: spherical / 3D metadata can take time to propagate so wait 1-2 hours before viewing the video.

**Comment by AsrielLewis** [comment] 2015-12-10 22:24
Thanks for all the help.

**Comment by suderman-google** [comment] 2015-12-11 18:51
No problem, happy to help!

**Comment by ako515** [comment] 2015-12-17 16:23
Hey guys! Any news in webm support? Or is there a solution for 8K video? Thanks.

**Comment by suderman-google** [comment] 2015-12-18 18:30
We do not have an implementation for webm at the moment however there are some alternative solutions. One suggestion is to save as a prores .mov file, change the extension to .mp4, inject metadata, and restore the mov extension.

This should work in most cases and we will be releasing an updated version with mov support shortly.

**Comment by dahnovka** [comment] 2016-03-18 18:20
Is there a standalone application for working with spatial audio? How to properly add it to the 360 video?

**Comment by henrynho** [comment] 2016-04-20 17:42
sorry I have a question I have a problem, I lower the 360 Video Metadata Tool.app of goolgle , but after using it in two videos, no longer works for me porq I get opened file,

any help please thanks

**Comment by xxraymoxx** [comment] 2016-04-20 17:44
Hi team

Ive been trying to use the standalone file for windows "360.Video.Metadata.Tool.win.exe" 

I get the error message: "This app can't run on your PC. To find a version for your PC, check with the software publisher"

I've scoured the internet results and it looks like there are no posts or suggestions anywhere on this issue. Any ideas?

Many thanks in advance for your help.

**Comment by suderman-google** [comment] 2016-04-20 18:15
The current version is not compatible with Windows 10. Are you using a windows 10 PC?

**Comment by henrynho** [comment] 2016-04-20 18:20
suderman-google:
friend a query when I open a video in Video Metadata Tool.app 360 Opened file tells me that means or where I find the file, can you help me please , Greetings

**Comment by dcower** [comment] 2016-04-20 18:57
Hi @henrynho and @xxraymoxx,

Could you please re-download the [latest Spatial Media Metadata Injector release](https://github.com/google/spatial-media/releases/latest/) and let us know if you are still having issues?

Thanks,
Dillon

**Comment by henrynho** [comment] 2016-04-20 22:14
when I open the video in the program tells me Opened file , I abjunto same image , I hope you can help me greetings
![captura de pantalla 2016-04-20 a las 5 09 06 p m](https://cloud.githubusercontent.com/assets/17299880/14692154/ff598e50-071a-11e6-80b1-985ebe16c3c4.png)
)

**Comment by dcower** [comment] 2016-04-20 22:25
Hi @henrynho,

After you open a file, you must check **Spherical** for a 360 video and **3D Top-bottom** if the video is stereoscopic (in a top-bottom/over-under layout). Finally, you must click **Save as** and save the injected video, which you can then upload to YouTube or other 360 video services.

Dillon

**Comment by henrynho** [comment] 2016-04-20 22:32
thanks and what I mean is that now I get opened file before he left me the option to save as, but now I get that message , greetings

**Comment by henrynho** [comment] 2016-04-20 22:56
because I get "Opened File" and how to fix it because I can not do save as the video, I hope you can understand , Greetings

**Comment by kotabelud** [comment] 2016-04-21 11:24
Hi guys. I keep getting "Fatal Error! Gui returned -1" when I tried running  "Spatial Media Metadata Injector.exe". What could be the problem? 
![error](https://cloud.githubusercontent.com/assets/18594140/14707308/a47815ba-07f6-11e6-94c2-53537b261756.jpg)

**Comment by dcower** [comment] 2016-04-21 15:28
Hi @kotabelud,

Could you share what version of Windows you're running, and whether your Windows is [32-bit or 64-bit](http://windows.microsoft.com/en-us/windows/32-bit-and-64-bit-windows)?

**Comment by dcower** [comment] 2016-04-21 15:38
@henrynho: If I understand correctly, the file opens but you're unable to check the boxes? Could you either attach a sample video here that exhibits the issue or email it to me ([myusername]@google.com)?

**Comment by soursquid** [comment] 2016-04-22 11:06
I'm running on windows 7 64-bit and having the same issue as @kotabelud , when i run the Spatial Media Metadata Injector app it says "Fatal Error! gui returned -1" and closes immediately.

**Comment by dcower** [comment] 2016-04-22 15:54
Hi @kotabelud and @soursquid,

Thanks for reporting and sorry about the inconvenience. I believe the issue should be fixed now. Could you please re-download the [latest release](https://github.com/google/spatial-media/releases/latest/) and let me know if the issue is fixed? Thanks!

**Comment by elotrosaulo** [comment] 2016-04-22 17:29
@dcower Hi! I just signed in to tell you that the latest release works perfectly!.

I wasn't able to open the app this morning (same issue described by @soursquid) , but now with the last update it works without any problem.

Thanks!!!

**Comment by dcower** [comment] 2016-04-22 17:37
@elotrosaulo: Excellent! Very glad to hear that. Thanks for letting us know!

**Comment by elotrosaulo** [comment] 2016-04-22 17:38
I wanted to tell you something too @dcower  (I dont know if it's normal of not). I tried this morning the Mac app (on a mac pro tower) and in more than 1 hour it couldn't do the encoding process (it has still the "Saving as..." message), but in Windows it took only 30 seconds to process the exactly same video.

**Comment by soursquid** [comment] 2016-04-22 18:45
@dcower Thanks for the fix, it's working perfectly fine now!

**Comment by jacalo** [comment] 2016-04-23 06:49
Hi, I just dowload the last version of the Spatial Media Metadata injector for mac (8.5.9).
Try to write on a H264 (.mp4) file edited and exported from after fx.
It let me load the file and select (spherical) but when I hit save in the destination window, just shows saving the file, but won't do anything. Any files came up, and just see the same interface.
Running Mac OS 10.10.5
Please help.
Thanks in advance.

JC
![screen shot 2016-04-22 at 11 48 02 pm](https://cloud.githubusercontent.com/assets/18626473/14759802/add21e64-08e4-11e6-92d7-1ab0abbe4285.png)
![screen shot 2016-04-22 at 11 48 33 pm](https://cloud.githubusercontent.com/assets/18626473/14759811/c1bea4a6-08e4-11e6-8f93-9669be3f6e43.png)



![screen shot 2016-04-22 at 11 47 01 pm](https://cloud.githubusercontent.com/assets/18626473/14759800/8b1b606a-08e4-11e6-942d-e19db3518bd9.png)
![screen shot 2016-04-22 at 11 42 08 pm](https://cloud.githubusercontent.com/assets/18626473/14759801/923491fa-08e4-11e6-9846-41e3e5d71a94.png)

**Comment by Splash62** [comment] 2016-04-24 15:53
Hi All. Running into similar problem as @jacalo @elotrosaulo I believe - File is permanently stuck on "saving file to...." even when run overnight on a small file.

Working on a .mp4 video
Running on OSX 10.9.5

Also - The file is 180 degrees only (half a sphere).  Do I need to do anything different for that?

Thanks in advance
E

**Comment by Ahurtado12** [comment] 2016-04-24 19:35
hi, i have a pixpro 360 4k camera that i have recorded videos on. When I try to run it trough the new metadata program it will not mix right. the top gets distorted and it shows a black hole when it shouldn't. i'm wondering if I download the old version of metadata (if i can find it) my videos will convert right without the blackhole on top. any suggestions on how i can fix this problem will be much appreciated. i should add that when i am edditing video on software it does not mix down with sound.

**Comment by dcower** [comment] 2016-04-25 15:59
@jacalo @Splash62 Could you try deleting the old version and re-downloading the [latest release](https://github.com/google/spatial-media/releases/latest) of the Spatial Media Metadata Injector to see if the issue still occurs? We've made a couple changes to the .zip downloads.

**Comment by dcower** [comment] 2016-04-25 16:02
@Ahurtado12 I believe the [PIXPRO software](http://kodakpixpro.com/Americas/support/downloads.php) (click "PIXPRO Software" on the top right of the page) should convert it to the YouTube-friendly format.

**Comment by Ahurtado12** [comment] 2016-04-25 20:31
@dcower  thanks but I am talking about after that step before uploading them to youtube, I was trying to put two different footage together into one in my video editor but once I've done that I cannot upload into youtube with pixpro program but when I save it trough Metadata a black hole appears on top of my video, why does this happen with the new Metadata software? Is there a link to the older vertigo where it was literally one click of a button?

**Comment by mrmcordellrob** [comment] 2016-04-25 21:15
@dcower Thanks. - I was having the same issue as @jacalo with the injector hanging while trying to save the injected file.  It is working for me again when using the latest release you linked.  I'm adding Spherical metadata to Equirectangular projection, without spatial audio on Mac.  Thanks for your help.

**Comment by Splash62** [comment] 2016-04-26 13:53
@dcower thanks! Re-downloading worked, the video saved (and quite quickly).

As an aside, is anyone else trying to view home-made 360 video on iOS?  With Kolor Eyes recently purchased by GoPro, I really don't see any good solutions.  How are others watching their 360 video on an iPhone?

**Comment by Splash62** [comment] 2016-04-26 14:03
To clarify, I mean viewing 360 video in a VR viewer such as Cardboard using an iphone.

**Comment by smasmonium** [comment] 2016-05-06 18:45
Not sure if this is quite the right thread for this question, but I took a 360 degree video with a Ricoh Theta S and am now trying to upload it to YouTube. Following these [instructions](https://support.google.com/youtube/answer/6178631?hl=en-GB), I downloaded the Spatial Media Metadata Injector for Mac, but first had to convert the camera's raw .m4v file into a .mov file using QuickTime in order for the Injector to process the file. I then did the injection and uploaded it to YouTube, but the orientation was wrong -- it thinks the "ground" is on the horizon line.

So the question is: Is there some way to use the Metadata Injector to correct the orientation? Or is there some other way to get correctly oriented data into a .m4v file taken using a Ricoh Theta S camera?

**Comment by dcower** [comment] 2016-05-06 20:59
@smasmonium Just to check, did you use [Ricoh Theta's software](https://theta360.com/en/support/download/) to convert the video into an equirectangular video first, or does it look like [this image](http://core0.staticworld.net/images/article/2015/09/150903-ricoh-ifa-3-100612252-large.jpg)?

**Comment by smasmonium** [comment] 2016-05-06 22:19
Thanks for the assistance Dillon. My video looks like the image you linked
to with two circles. When I tried downloading Ricoh "Basic App" for Mac
from Ricoh's software site, it didn't seem able to open the raw .m4v file
for the 360 degree video generated by the Ricoh Theta S camera, so I'm not
sure how to "convert" it. The "Live-Streaming App" didn't seem to work
either. Thoughts?

**Comment by rengelmann** [comment] 2016-05-07 19:59
@smasmonium I think the only path Ricoh has given to convert their video files from fisheye to equirectangular is to import them from the camera into their mobile app first. Then transfer that resulting movie from your phone to your computer, and finally upload that to Facebook or YouTube. I just tested it again now and YouTube recognized it as a 360 video without running it through the metadata injector.

Unless you are in live mode and using the THETA UVC Blender capture. That works well with OBS or XSplit and YouTube.

**Comment by Splash62** [comment] 2016-05-08 01:17
Running into the most frustrating issue, I feel like I'm not totally understanding the overall process.

I have video recorded on a PixPro SP360 4K. Goal is to view footage on Cardboard using an iPhone.

Do you have to inject metadata to view any video in 360 (not just on youtube)?

The Pixpro app even uploaded a new VR viewer function, but it doesn't seem to work to be selectable.

Anyone else facing the same problem?

**Comment by dcower** [comment] 2016-05-31 18:25
Hi everyone, I'm closing this issue since it has devolved to cover a variety of issues, many of which are now fixed. :) Please open separate issues if you have any additional problems/questions. Thanks!

**Closed by dcower** 2016-05-31 18:25 UTC
Labels: spherical video

**Comment by Boscop** [comment] 2020-05-29 13:12
@jprouty @dcower I've been looking at [this](https://github.com/google/spatial-media/tree/master/spatialmedia) doc, but it's still not clear to me which CLI flags I have to use when I have an equirectangular video. Can you please tell me which flags I should use? :)
(To automate the process / not using the GUI)
