### ISSUE TITLE
Error while loading Samsung Gear 360 videos

### ISSUE THREAD

**Issue by VoodooDE** [google/spatial-media#202] opened 2018-06-10 17:17 UTC
![gear360](https://user-images.githubusercontent.com/13249160/41204286-c51f17f2-6ce2-11e8-98dc-10cd37987e22.jpg)

I have problems using the tool for my Samsung Gear 360 (2017).
Last year it worked with the same videos, but now it doesnt.
As soon as I try to open the files, this error occurs.
Can you help me with that?

**Comment by kabkee** [comment] 2018-06-12 00:42
I got the same one.

**Comment by VoodooDE** [comment] 2018-06-14 22:27
So nobody can help here?

**Comment by kabkee** [comment] 2018-06-15 00:19
@VoodooDE Not yet I think... 
I start studying python yesterday lol.

**Comment by emontellese** [comment] 2018-06-20 05:03
Same issue

**Comment by emontellese** [comment] 2018-06-20 05:36
The issue occurs in the user interface portion only.  You can inject files with metadata using the commandline -- but this is unfortunately difficult for users unfamiliar with commandline tools.

The error occurs when the program attempts to *read* the existing metadata.  If your file has no metadata it fails and dies.

For developers who want to fix it -- the fix should be rather simple: just handle the error and let the GUI continue (so the user can click the 'inject' button).  I may investigate it in the future, but have limited time for awhile.

**Comment by kabkee** [comment] 2018-06-20 06:08
Unfortunately, at the moment,  the solution is that if you have Adobe premiere, you may convert the video with 360 video metadata :(

**Comment by Boscop** [comment] 2018-07-23 23:22
@VoodooDE Maybe it works after converting it with VLC? Did you try that?

**Comment by Chilliane** [comment] 2018-08-02 03:45
I have the same issue

**Comment by BigKahunaFSU** [comment] 2018-12-25 14:02
> 
> 
> I have the same issue
> I have looked around for possible fix and i got this one
> https://github.com/google/spatial-media/tree/master/spatialmedia
> It has some line of codes that can you run on python however I am no coder on python and the codes does not explain how to target the file.

Did you get this to work? I'm in need of a fix bad.  The videos of my daughter opening her Christmas presents aren't working.

**Comment by Chilliane** [comment] 2018-12-26 04:14
Was not able to confirm, you can try
Seems the all you need to do is install python and spatialmedia and run
command

python spatialmedia -i [--stereo=(none|top-bottom|left-right)]
[--spatial-audio] <input> <output>

<input> = video.mp4

<output> = injectedvideo.mp4

Tell me if it worked

**Comment by tonytone23** [comment] 2019-02-11 19:09
I use the Samsung software to stitch (1) and then facebook https://www.facebook.com/360_media/create to process the file (2), then I can inject (3). This is very cumbersome and I don't understand what's going on. Is there a way to streamline for Samsung 360 videos?

**Comment by DeliberatelyOmitted** [comment] 2019-03-18 18:41
I am looking for what Youtube refers to simply as the metadata injector so I can upload 360 videos in fully functional mode.  What i am finding here (which is where Google points me) is a clusterfuck (pardon my French) of frustrating dialog which leaves me with the impression there is really no viable way to perform this vital function, yet there are those who profess to know how but lack the ability to explain it to others.

Does anyone here speak "normal-speak" so that a simpleton such as myself can go on with my boring life and successfully upload my 360 videos from my Samsung 360 without banging my had against my keyboard more than I already have?

Thanks.

**Comment by tonytone23** [comment] 2019-03-18 22:19
There are two steps:

1. Stitch the video using the software from Samsung - watch this:
https://www.youtube.com/watch?v=2Fok2YcyNSw

2. Inject the metadata to tell YouTube and Facebook that the stitched video
is 360. - goto this page:
https://support.google.com/youtube/answer/6178631?hl=en, download
https://github.com/google/spatial-media/releases/tag/v2.1

I'm stuck on #2, even after I inject metadata, I still can't upload the
video as 360.

Tony

**Comment by kenyob** [comment] 2019-04-05 02:21
Im having the same issue.
Any fixes on this?

**Comment by antoniobejar** [comment] 2019-04-13 00:58
I've just solved it.
The issue is the script tries 'changing' 360 video metadata but, first time, doesn't exist. So, first step is opening 'https://www.facebook.com/360_media/create', select you video for manipulating it and press download. Now you get a '_edited'version of the file which, now, can be succesfully processed by spatial-media.
Hope that helps.

**Comment by anuragchauhan00** [comment] 2021-10-31 11:38
thanks @antoniobejar !
as it is FB am bit conscious of privacy of videos being converted.

Any idea if this utility can work for Samsung 360?
am soo glad to find this thread, for last 3 weeks i was thinking am doing something wrong :(

**Comment by acem77** [comment] 2022-04-27 02:23
same issue any hope of this being updated to ignore the missing meta data? or any other tools to use to create dummy meta data or replaces this?
i will try to learn some python. my smooth brain cant even navigate dirs yet..

thanks

**Comment by acem77** [comment] 2022-04-27 19:29
getting this with the python version

D:\360\spatial-media-2.1>python spatialmedia -i D:\360\test.mp4 D:\360\testout.mp4
Processing: D:\360\test.mp4
Saved file settings
        Track 0
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\360\spatial-media-2.1\spatialmedia\__main__.py", line 127, in <module>
    main()
  File "D:\360\spatial-media-2.1\spatialmedia\__main__.py", line 106, in main
    metadata_utils.inject_metadata(args.file[0], args.file[1], metadata,
  File "D:\360\spatial-media-2.1\spatialmedia\..\spatialmedia\metadata_utils.py", line 430, in inject_metadata
    inject_mpeg4(infile, outfile, metadata, console)
  File "D:\360\spatial-media-2.1\spatialmedia\..\spatialmedia\metadata_utils.py", line 381, in inject_mpeg4
    parse_spherical_mpeg4(mpeg4_file, in_fh, console)
  File "D:\360\spatial-media-2.1\spatialmedia\..\spatialmedia\metadata_utils.py", line 327, in parse_spherical_mpeg4
    parse_spherical_xml(contents.decode("utf-8"), console)
  File "D:\360\spatial-media-2.1\spatialmedia\..\spatialmedia\metadata_utils.py", line 282, in parse_spherical_xml
    for child in parsed_xml.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

D:\360\spatial-media-2.1>python spatialmedia -i D:\360\test.mp4 D:\360\testout.mp4

**Comment by sblackstein** [comment] 2022-10-25 02:17
BTW, for those still struggling with this, the fix is indeed to skip enumeration of existing tags and the injection proceeds just fine where YouTube sees the video as a 360. Just insert `return sphericalDictionary` as a new line before line 282 in `parse_spherical_xml()` in spatialmedia/metadata_utils.py to return early.

**Closed** 2024-12-01 19:06 UTC
