### ISSUE TITLE
Files with non-ASCII paths break the injector

### ISSUE THREAD

**Issue by sergeydolya** [google/spatial-media#85] opened 2016-05-21 12:32 UTC
Hi, 

Spatial doesn’t work on my mac no matter what I do. Can you help?

I can open it and I can open the file, but it won’t let me check the boxes or press Save As button: 

![2016-05-21 15 25 49](https://cloud.githubusercontent.com/assets/19504630/15448376/244ffab2-1f69-11e6-822e-733e4bf3f175.png)

I can’t open any file and the same files opens perfectly at macs of my friends. 

How can I fix it? Thank you

Here is the sample file, that I am trying to use: https://www.dropbox.com/s/jj5tukj273vbd12/360%202.mp4?dl=0

**Comment by dcower** [comment] 2016-06-01 20:12
Hi @sergeydolya, sorry you're having this issue. Could you download the [latest version of the Spatial Media Metadata Injector](https://github.com/google/spatial-media/releases/latest) and let us know if the issue persists? Could you also share what version of OS X and what computer you have? Thanks!

**Comment by sergeydolya** [comment] 2016-06-01 21:12
Hi!

I downloaded the latest version but it didn’t help. 

This is info about my computer: 



Is it possible that I am having this problem because I use Russian language on my computer? 


С уважением,
Сергей Доля


e-mail: sergeydolya@gmail.com
http://sergeydolya.livejournal.com

**Comment by dcower** [comment] 2016-06-01 23:15
Hi @sergeydolya, it looks like your computer info was lost somewhere along the line. If it helps, you can email it to me at [my username]@google.com. We haven't tested the injector with Russian language before, so that could be it.

**Comment by sergeydolya** [comment] 2016-06-04 21:02
Dear Dillon,

I’ve switched my computer to english language, but it didn’t help :(

I am using apple macbook pro with retina display 15" mid 2015

OS X El Capitan
10.11.5

2,5 Пря Intel Core i7
16 Gb 1600 Mghs DDR3




С уважением,
Сергей Доля


e-mail: sergeydolya@gmail.com
http://sergeydolya.livejournal.com

**Comment by pwroberts** [comment] 2016-06-08 05:26
Hi Sergey,

I'm sorry changing the language didn't help!

We have updated the injector app again - it should now display an error dialog in cases where the GUI might have silently failed before. We also simplified the UI a bit.

Could you download the app again from [the latest release page](https://github.com/google/spatial-media/releases/latest) and try your sample file? If you see an error dialog this time, please paste the contents here.

I also confirmed your sample file works OK in the injector for me.

Thanks,

Paul

**Comment by pwroberts** [comment] 2016-06-08 23:54
@nandico Thanks for sharing your experience - and no problem! I'm glad the error dialog was helpful.

Would you mind sharing the stack trace you saw? (You can select/copy/paste text from the error dialog.) I'd like us to fix the underlying bug, or at least add a more helpful error message for that specific case.

**Comment by nandico** [comment] 2016-06-09 03:09
Sorry, @pwroberts - I made a mistake. I think my Goggle Drive was linked to an external unity but the GDRIVE path is inside my main hd on Mac OS. Probably is not an FAT32 issue. Sorry for the bad report.

Something happened on my Google Drive - Photoshop started to complain about file naming when I export files directly to any point in my Google Drive file structure, talking about "non-Latin characters" on filenames and replacing spaces by dashes. I think is some kind of path translation problem. When I move a video file to Desktop or other common folder in my Mac, the Spatial Metadata Injector works perfectly.

My stack trace is:

{Traceback (most recent call last):
} {  File "lib-tk/Tkinter.py", line 1536, in __call__
} {  File "<string>", line 66, in action_open
} {  File "spatialmedia/metadata_utils.py", line 384, in parse_metadata
} {  File "<string>", line 50, in append
} UnicodeEncodeError:\ 'ascii'\ codec\ can't\ encode\ character\ u'\\u0303'\ in\ position\ 61:\ ordinal\ not\ in\ range(128)\

**Comment by dcower** [comment] 2016-06-27 23:39
This should be fixed now. Also see issue #95.

**Closed by dcower** 2016-06-27 23:39 UTC
Labels: bug, injector, spherical video
