### ISSUE TITLE
How to use it on Linux?

### ISSUE THREAD

**Issue by ProgrammingLife** [google/spatial-media#248] opened 2020-09-22 23:49 UTC
How to use it on Linux? Can you provide me with a little example?

**Comment by iwanttobefreak** [comment] 2020-10-26 13:44
git clone https://github.com/google/spatial-media
cd spatial-media/spatialmedia
./gui.py

It opens gui application. Select video with open button and then select if your video is spherical (360º) or stereoscopic (top/bottom) and then "inject metadata" button

**Comment by EndeavourAccuracy** [comment] 2021-06-29 15:17
> git clone https://github.com/google/spatial-media
> cd spatial-media/spatialmedia
> ./gui.py
> 
> It opens gui application. Select video with open button and then select if your video is spherical (360º) or stereoscopic (top/bottom) and then "inject metadata" button

It's unclear to me why @atrauzzi gave your post a thumbs down.
It works for me.
One additional step that might be necessary for some is:
`sudo apt install python-tk`

**Comment by ambein** [comment] 2021-09-26 18:28
Works, had to run it in pyhton2 on my system (after installation of python-tk). So the solution for me was:

```
sudo apt install python-tk
git clone https://github.com/google/spatial-media
cd spatial-media/spatialmedia
python2 gui.py
```
Thanks everyone!

**Comment by clort81** [comment] 2022-04-20 12:35
No text except "Inject metadata" displayed.

on debian using python-tk (2.7.18-1) ...
python2 gui.py

**Comment by Moilleadoir** [comment] 2023-01-20 05:29
Is globally installing `python-tk` really best practice?  Is this still Python 2?

**Comment by jamiesonpepper** [comment] 2023-01-22 01:22
There are a few forks that have [added support to 3.9 and later](https://github.com/DeepakThi/spatial-media), and I believe there is an outstanding merge/pull to add GUI support for Python 3 GUI as well https://github.com/google/spatial-media/pull/227 [fork is here](https://github.com/movalex/spatial-media).

**Comment by Moilleadoir** [comment] 2023-01-22 03:59
Thanks!

**Comment by aruku7230** [comment] 2023-01-29 10:15
This worked for me on Ubuntu 20.04

```bash
# python3-tk is installed. python-tk is not installed.
git clone https://github.com/google/spatial-media
cd spatial-media/spatialmedia
python3 ./gui.py
```

**Comment by jamiesonpepper** [comment] 2023-01-29 13:56
I've recently merged a bunch of community fixes into master which added support for Python3. Hoping to kick off a release sometime in the next couple of weeks once I have some VMs setup for testing.

**Comment by allegfede** [comment] 2024-05-02 08:51
ubuntu 22.04

i can confirm that:
sudo apt install python-tk
git clone https://github.com/google/spatial-media
cd spatial-media/spatialmedia
python2 gui.py

worked perfectly.

Only bug i noticed, the extention of the files have to be lowercase, or thay are not show in the open dialog interface :-)

**Closed** 2024-12-01 19:07 UTC
